# 1章 ニューラルネットワークの復習

## 1.1 数学とPythonの復習

### 1.1.1 ベクトルと行列

In [18]:
import numpy as np

x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [19]:
x_list = list(x)
x_list.__class__

list

In [20]:
x.shape

(3,)

In [21]:
x.ndim

1

In [22]:
w = np.array([[1, 2, 3], [4, 5, 6]])
w.shape

(2, 3)

In [23]:
# w の2列目
w[:, 1]

array([2, 5])

In [24]:
w.ndim

2

`Numpy` ライブラリは, 数値計算を効率的に行うライブラリ. 特に配列や行列の操作に強い.  
`np.array()` メゾットでベクトルや行列を生成することが可能.  
`x.__class__` は `x` が作成されたすべてのクラス名, メゾット, 属性などの情報を返す.  
 `numpy.ndarray` は numpyの多次元配列  
`x.shape` は, `x` 多次元配列の形状を表す.  
`x.ndim` は, `x` の次元数を表す.

### 1.1.2 行列の要素後との演算

In [25]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [26]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

`numpy` の多次元配列に対して, `+` や `*` などの四則演算を行っている.

### 1.1.3 ブロードキャスト

In [27]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [28]:
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

`ndarray` 同士の二項演算ではブロードキャストという仕組みによりそれぞれの形状 `shape` が同じになるように自動的に変換される.

### 1.1.4 ベクトルの内積と行列の積

In [29]:
# ベクトルの内積
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [30]:
# 行列の積
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

`np.dot()` はベクトルの内積と行列の積の計算に使える.

### 1.1.5 行列の形状チェック

$3\times 2$ の行列 $\mathbf{A}$ と $2\times 4$ の行列 $\mathbf{B}$ によって $3\times 4$ の行列 $\mathbf{C}$ が生成される. この時, 行列 $\mathbf{A}$ と  $\mathbf{B}$ の対応する次元の要素数を一致させる必要がある.

In [34]:
W

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
W.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
W.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])